# Use postgres/example user/password credentials
version: '3.5'

services:
  s3-platform-node:
    container_name: ${SPP_CONTAINER_NAME}
    platform: linux/amd64
    build:
      context: .
      dockerfile: dev.Dockerfile
    networks:
      - s3p-inner-net
      - s3p-selenium-net
    hostname: s3p-node-main
#    depends_on:
#      - chrome-webdriver
    environment:
      - NODE_NAME=s3p-node
      - NODE_IP=-1
      - NODE_TYPES=SOURCE
    volumes:
      - type: bind # директория для логов
        source: ./${SPP_LOG_TEMP_PATH}
        target: /sppnode/${SPP_LOG_TEMP_PATH}
      - type: bind # архив плагинов
        source: ./${PL_BASE_TEMP_DIR}
        target: /sppnode/${PL_BASE_TEMP_DIR}
      - type: bind # локальное хранилище
        source: ./${LS_BASE_TEMP_DIR}
        target: /sppnode/${LS_BASE_TEMP_DIR}
#  chrome-webdriver:
#    platform: linux/amd64
#    image: selenium/standalone-chrome:latest
#    hostname: selenium-remote-webdriver
#    networks:
#      - s3p-selenium-net
#    ports:
#      - 4444:4444
#    privileged: true
#    shm_size: 2g


networks:
  s3p-selenium-net:
    driver: bridge
  s3p-inner-net:
    external: true