from ..abc_repository import ABCRepository


class AbcControlRepository(ABCRepository):

    def initialize(self): ...

    def alive(self): ...

    def next(self): ...

    def status_update(self, plugin, status): ...

    def broke(self): ...

    def finish(self): ...
