NONSET = 0
AWAITING = 10
PREPARING = 20
READY = 30
WORKING = 40
SUSPENDED = 50
FINISHED = 60
BROKEN = 70
TERMINATED = 80

_statusToName = {
    NONSET: "NONSET",
    AWAITING: "AWAITING",
    PREPARING: "PREPARING",
    WORKING: "WORKING",
    READY: "READY",
    SUSPENDED: "SUSPENDED",
    FINISHED: "FINISHED",
    BROKEN: "BROKEN",
    TERMINATED: "TERMINATED",
}

_nameToStatus = {
    "NONSET": NONSET,
    "AWAITING": AWAITING,
    "PREPARING": PREPARING,
    "WORKING": WORKING,
    "READY": READY,
    "SUSPENDED": SUSPENDED,
    "FINISHED": FINISHED,
    "BROKEN": BROKEN,
    "TERMINATED": TERMINATED,
}
